version: '2'

services:
  seafile:
    build: .
    links:
      - mysql
    volumes:
      - ./var/seafile:/seafile
      - ./etc/ssl/private:/etc/ssl/private
    ports:
      - 9080:80

  mysql:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    image: mysql:5.7
